apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    app: {{ include "redisinsight.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redisinsight.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redisinsight.name" . }}
    spec:
      containers:
        - name: redisinsight
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - name: db
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: db
          emptyDir: {}

